name = "aurelis-authority"
compatibility_date = "2026-10-07"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "aurelis-authority"
database_id = "9409cc56-5113-4910-af66-cf29d45466b2"
