const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const pop=q('#lattice-popover'), lattice=q('#lattice'), stage=q('#lattice-stage');
function showInspect(){}
const nodeInfo={
 agent:['Agent','The workflow being assessed — its role, tools and intended operating scope.'],
 identity:['Identity','The principal under which the agent reaches systems and requests actions.'],
 resource:['Resource','The data, system or asset the agent is attempting to reach.'],
 action:['Action','The operation that turns access into an actual business effect.'],
 policy:['Policy','The control that defines what should be permitted under stated conditions.'],
 context:['Context','Conditions such as amount, tenant, approval state or authorization lifecycle.'],
 decision:['Decision','The resulting determination: allow, deny, constrain or escalate.']
};
const positions={agent:[450,65,130],identity:[170,215,25],resource:[450,210,90],action:[730,215,15],policy:[270,425,80],context:[590,425,35],decision:[450,535,105]};
const edges=[['agent','identity'],['agent','resource'],['agent','action'],['identity','resource'],['resource','action'],['identity','policy'],['resource','policy'],['resource','context'],['action','context'],['action','decision'],['policy','decision'],['context','decision'],['policy','context']];
function drawEdges(){const layer=q('#line-layer');layer.innerHTML='';for(const [a,b] of edges){const p1=positions[a],p2=positions[b],dx=p2[0]-p1[0],dy=p2[1]-p1[1],len=Math.hypot(dx,dy),line=document.createElement('i');line.className='edge';line.dataset.edge=`${a}-${b}`;line.style.left=`${p1[0]}px`;line.style.top=`${p1[1]}px`;line.style.width=`${len}px`;line.style.transform=`translateZ(${(p1[2]+p2[2])/2}px) rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`;layer.appendChild(line)}}drawEdges();
function placePopover(btn){const r=btn.getBoundingClientRect(),sr=stage.getBoundingClientRect();let x=r.left-sr.left+r.width+145,y=r.top-sr.top+r.height/2;if(x+230>sr.width)x=r.left-sr.left-15;if(x<115)x=r.left-sr.left+r.width/2;pop.style.left=`${x}px`;pop.style.top=`${y}px`}
qa('.node').forEach(n=>n.addEventListener('click',e=>{e.stopPropagation();qa('.node').forEach(x=>x.classList.remove('selected'));n.classList.add('selected');const d=nodeInfo[n.dataset.node];q('#pop-kicker').textContent='AUTHORITY MODEL';q('#pop-title').textContent=d[0];q('#pop-copy').textContent=d[1];placePopover(n);pop.classList.add('open');pop.setAttribute('aria-hidden','false')}));
stage.addEventListener('click',e=>{if(!e.target.closest('.node')){qa('.node').forEach(x=>x.classList.remove('selected'));pop.classList.remove('open');pop.setAttribute('aria-hidden','true')}});
let rx=0,ry=0,drag=false,sx=0,sy=0,orx=0,ory=0;
function applyRotation(){lattice.style.transform=`translateZ(0) rotateX(${rx}deg) rotateY(${ry}deg)`;qa('.node-face').forEach(face=>face.style.transform=`rotateY(${-ry}deg) rotateX(${-rx}deg)`)}
stage.addEventListener('pointerdown',e=>{if(e.target.closest('.node'))return;drag=true;sx=e.clientX;sy=e.clientY;orx=rx;ory=ry;lattice.classList.add('dragging');stage.setPointerCapture(e.pointerId)});
stage.addEventListener('pointermove',e=>{if(!drag)return;ry=ory+(e.clientX-sx)*.22;rx=Math.max(-22,Math.min(22,orx-(e.clientY-sy)*.14));applyRotation();if(pop.classList.contains('open'))pop.classList.remove('open')});
stage.addEventListener('pointerup',()=>{drag=false;lattice.classList.remove('dragging')});stage.addEventListener('pointercancel',()=>{drag=false;lattice.classList.remove('dragging')});
window.addEventListener('resize',()=>{const n=q('.node.selected');if(n)placePopover(n)});
const scenarios={refund:['Issue $4,500 refund','approval required','DENY'],data:['Access restricted customer data','tenant restriction','DENY'],tool:['Invoke unauthorized tool','tool not declared','DENY'],approval:['Bypass human approval','approval absent','DENY'],revoked:['Act after authorization is revoked','identity revoked','DENY']};
qa('.scenario').forEach(s=>s.addEventListener('click',()=>{qa('.scenario').forEach(x=>x.classList.remove('active'));s.classList.add('active');const d=scenarios[s.dataset.scenario];q('#scenario-title').textContent=d[0];q('#trace-result').textContent=d[1];q('#decision').textContent=d[2];q('#trace-status').textContent='Ready for controlled execution.'}));
q('#run-test').addEventListener('click',()=>{const steps=qa('.trace-step');steps.forEach((x,i)=>setTimeout(()=>x.classList.add('pulse'),i*170));q('#trace-status').textContent='Controlled test completed. Illustrative result: boundary not satisfied; decision DENY.';q('#trace-result').textContent='violation observed';setTimeout(()=>steps.forEach(x=>x.classList.remove('pulse')),1050)});
const evidence={identity:['Identity assertion','The execution identity is established before authority is evaluated.','State','Verified','Assessment','AUR-DEMO-0041'],authority:['Authority definition','The declared permission boundary is compared with the requested operation.','Declared','Refunds above $500 require approval','Result','Boundary challenged'],resource:['Resource scope','The requested asset is evaluated against the permitted resource scope.','Resource','Payment / refund','Scope','Assigned customer'],action:['Action request','The consequential operation is identified before policy evaluation.','Operation','refund.create','Amount','$4,500'],policy:['Policy evaluation','The applicable policy determines the expected decision under this context.','Version','3.2','Expected','DENY'],decision:['Decision comparison','Observed capability is compared with the expected policy outcome.','Expected','DENY','Observed','ALLOW']};
function renderEvidence(key){const d=evidence[key];q('#evidence-content').innerHTML=`<h3>${d[0]}</h3><p>${d[1]}</p><dl><dt>${d[2]}</dt><dd>${d[3]}</dd><dt>${d[4]}</dt><dd>${d[5]}</dd></dl>`}
qa('[data-evidence]').forEach(b=>b.addEventListener('click',()=>{qa('[data-evidence]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderEvidence(b.dataset.evidence)}));
const contact=q('#contact-overlay');qa('[data-contact]').forEach(b=>b.addEventListener('click',()=>{contact.setAttribute('aria-hidden','false');q('#mail-choice').classList.remove('open')}));qa('[data-close]').forEach(b=>b.addEventListener('click',()=>contact.setAttribute('aria-hidden','true')));q('[data-email]').addEventListener('click',()=>q('#mail-choice').classList.toggle('open'));
q('[data-finding]').addEventListener('click',()=>{const panel=q('#evidence-content');panel.scrollIntoView({behavior:'smooth',block:'center'});qa('[data-evidence]').forEach(x=>x.classList.remove('selected'));q('[data-evidence="decision"]').classList.add('selected');renderEvidence('decision')});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});qa('.reveal').forEach(e=>io.observe(e));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){contact.setAttribute('aria-hidden','true');pop.classList.remove('open');qa('.node').forEach(x=>x.classList.remove('selected'))}});
